version: '3'
services:
  # Front-end service (Node.js app)
  frontend:
    build: .
    ports:
      - "8080:3000"  # Expose port 3000 inside container to 8080 on the host
    networks:
      - ecommerce-network
    depends_on:
      - shopping-cart

  # MongoDB service (Database)
  shopping-cart:
    image: mongo
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
    networks:
      - ecommerce-network
    ports:
      - "27017:27017"  # Expose MongoDB port

  # Mongo Express service (Graphical UI for MongoDB)
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"  # Expose Mongo Express interface
    depends_on:
      - shopping-cart
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://shopping-cart:27017  # Connect Mongo Express to MongoDB
    networks:
      - ecommerce-network

  # Nginx service (Proxy server)
  nginx:
    build: ./nginx  # Build Nginx from the nginx folder (where we put the Dockerfile and nginx.conf)
    ports:
      - "443:443"  # Expose HTTPS port
    depends_on:
      - frontend
    networks:
      - ecommerce-network
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl  # Bind your nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

# Define a shared network for the services
networks:
  ecommerce-network:
    driver: bridge

# Define volumes to persist data
volumes:
  mongo-data:
